-- Tablas del sistema Taller JB.
--
-- El sistema ejecuta este script solo la primera vez que conecta, cada vez que
-- se abre. Crea unicamente las tablas que todavia no existen ("IF NOT EXISTS"):
-- en una base que ya tiene las tablas no cambia nada ni borra datos.
--
-- Es la misma estructura que creaba antes el Hibernate (mismos nombres de
-- tablas, columnas y valores permitidos), asi una base creada antes sigue
-- funcionando igual.

CREATE TABLE IF NOT EXISTS usuario (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activo boolean NOT NULL,
    clave varchar(255) NOT NULL,
    login varchar(60) NOT NULL,
    nombre varchar(120) NOT NULL,
    permiso_cancelar_os boolean DEFAULT false NOT NULL,
    permiso_cierre_mensual boolean DEFAULT false NOT NULL,
    permiso_clientes_maquinarios boolean NOT NULL,
    permiso_compras_proveedores boolean NOT NULL,
    permiso_editar_empleados boolean DEFAULT false NOT NULL,
    permiso_eliminar_registros boolean DEFAULT false NOT NULL,
    permiso_empleados_socios boolean NOT NULL,
    permiso_financiero boolean NOT NULL,
    permiso_movimiento_manual boolean DEFAULT false NOT NULL,
    permiso_ordenes_servicio boolean NOT NULL,
    permiso_pagar_salario boolean DEFAULT false NOT NULL,
    permiso_retirar_saldo boolean DEFAULT false NOT NULL,
    permiso_retiros_empleado boolean DEFAULT false NOT NULL,
    permiso_socios boolean DEFAULT false NOT NULL,
    permiso_usuarios boolean NOT NULL,
    CONSTRAINT usuario_login_uk UNIQUE (login)
);

CREATE TABLE IF NOT EXISTS socio (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activo boolean NOT NULL,
    documento varchar(30),
    nombre varchar(120) NOT NULL,
    telefono varchar(30)
);

CREATE TABLE IF NOT EXISTS empleado (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activo boolean NOT NULL,
    cargo varchar(80),
    documento varchar(30),
    fecha_admision date,
    nombre varchar(120) NOT NULL,
    salario_base numeric(14,2),
    telefono varchar(30)
);

CREATE TABLE IF NOT EXISTS cliente (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    direccion varchar(200),
    documento varchar(30),
    nombre varchar(120) NOT NULL,
    saldo numeric(14,2) NOT NULL,
    telefono varchar(30)
);

CREATE TABLE IF NOT EXISTS maquinario (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identificacion varchar(30),
    marca varchar(60),
    modelo varchar(60),
    observacion varchar(200),
    tipo varchar(30) NOT NULL,
    cliente_id bigint NOT NULL REFERENCES cliente(id),
    CONSTRAINT maquinario_tipo_check CHECK (tipo IN
        ('CAMION', 'TRACTOR', 'COSECHADORA', 'IMPLEMENTO_AGRICOLA', 'OTRO'))
);

CREATE TABLE IF NOT EXISTS proveedor (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contacto varchar(120),
    documento varchar(30),
    nombre varchar(120) NOT NULL,
    saldo numeric(14,2) NOT NULL,
    telefono varchar(30)
);

CREATE TABLE IF NOT EXISTS orden_de_servicio (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    estado varchar(20) NOT NULL,
    fecha_apertura date NOT NULL,
    fecha_cierre date,
    numero bigint NOT NULL,
    problema_reportado varchar(500),
    valor_total numeric(14,2) NOT NULL,
    cliente_id bigint NOT NULL REFERENCES cliente(id),
    maquinario_id bigint REFERENCES maquinario(id),
    CONSTRAINT orden_de_servicio_numero_uk UNIQUE (numero),
    CONSTRAINT orden_de_servicio_estado_check CHECK (estado IN
        ('ABIERTA', 'EN_PROCESO', 'CONCLUIDA', 'CANCELADA'))
);

CREATE TABLE IF NOT EXISTS item_orden_servicio (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cantidad numeric(12,3) NOT NULL,
    descripcion varchar(200) NOT NULL,
    tipo varchar(20) NOT NULL,
    valor_total numeric(14,2) NOT NULL,
    valor_unitario numeric(14,2) NOT NULL,
    orden_de_servicio_id bigint NOT NULL REFERENCES orden_de_servicio(id),
    CONSTRAINT item_orden_servicio_tipo_check CHECK (tipo IN ('SERVICIO', 'REPUESTO'))
);

CREATE TABLE IF NOT EXISTS compra (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha date NOT NULL,
    numero bigint NOT NULL,
    valor_total numeric(14,2) NOT NULL,
    proveedor_id bigint NOT NULL REFERENCES proveedor(id),
    CONSTRAINT compra_numero_uk UNIQUE (numero)
);

CREATE TABLE IF NOT EXISTS item_compra (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cantidad numeric(12,3) NOT NULL,
    descripcion varchar(200) NOT NULL,
    valor_total numeric(14,2) NOT NULL,
    valor_unitario numeric(14,2) NOT NULL,
    compra_id bigint NOT NULL REFERENCES compra(id)
);

CREATE TABLE IF NOT EXISTS cierre_mensual (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descripcion varchar(100),
    fechacierre date NOT NULL,
    gananciatotal numeric(14,2) NOT NULL,
    totalentradas numeric(14,2) NOT NULL,
    totalsalidas numeric(14,2) NOT NULL
);

CREATE TABLE IF NOT EXISTS cierre_socio_detalle (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parteganancia numeric(14,2) NOT NULL,
    valorarecibir numeric(14,2) NOT NULL,
    yaretirado numeric(14,2) NOT NULL,
    cierre_id bigint NOT NULL REFERENCES cierre_mensual(id),
    socio_id bigint NOT NULL REFERENCES socio(id)
);

CREATE TABLE IF NOT EXISTS movimiento_financiero (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    categoria varchar(30) NOT NULL,
    descripcion varchar(200),
    descuento_porcentaje numeric(5,2),
    descuento_valor numeric(14,2),
    fecha date NOT NULL,
    tipo varchar(10) NOT NULL,
    valor numeric(14,2) NOT NULL,
    cierre_id bigint REFERENCES cierre_mensual(id),
    cliente_id bigint REFERENCES cliente(id),
    empleado_id bigint REFERENCES empleado(id),
    proveedor_id bigint REFERENCES proveedor(id),
    CONSTRAINT movimiento_financiero_categoria_check CHECK (categoria IN
        ('PAGO_CLIENTE', 'COMPRA_PROVEEDOR', 'SALARIO_EMPLEADO', 'DEVOLUCION_CLIENTE',
         'DEVOLUCION_PROVEEDOR', 'OTRO')),
    CONSTRAINT movimiento_financiero_tipo_check CHECK (tipo IN ('ENTRADA', 'SALIDA'))
);

CREATE TABLE IF NOT EXISTS retiro_empleado (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha date NOT NULL,
    fechaliquidacion date,
    liquidado boolean NOT NULL,
    observacion varchar(200),
    tipo varchar(20) NOT NULL,
    valor numeric(14,2) NOT NULL,
    empleado_id bigint NOT NULL REFERENCES empleado(id),
    pago_salario_id bigint REFERENCES movimiento_financiero(id),
    CONSTRAINT retiro_empleado_tipo_check CHECK (tipo IN ('VALE_SEMANAL', 'ADELANTO', 'OTRO'))
);

CREATE TABLE IF NOT EXISTS retiro_socio (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha date NOT NULL,
    observacion varchar(200),
    valor numeric(14,2) NOT NULL,
    cierre_id bigint REFERENCES cierre_mensual(id),
    socio_id bigint NOT NULL REFERENCES socio(id)
);

CREATE TABLE IF NOT EXISTS cheque_predatado (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    banco varchar(80),
    descripcion varchar(200),
    descuento_porcentaje numeric(5,2),
    descuento_valor numeric(14,2),
    estado varchar(12) NOT NULL,
    fecha_confirmacion date,
    fecha_registro date NOT NULL,
    fecha_vencimiento date NOT NULL,
    numero_cheque varchar(40),
    valor numeric(14,2) NOT NULL,
    cliente_id bigint REFERENCES cliente(id),
    proveedor_id bigint REFERENCES proveedor(id),
    CONSTRAINT cheque_predatado_estado_check CHECK (estado IN ('PENDIENTE', 'CONFIRMADO'))
);

CREATE TABLE IF NOT EXISTS registro_auditoria (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    accion varchar(60) NOT NULL,
    detalle varchar(500),
    fecha_hora timestamp(6) without time zone NOT NULL,
    usuario_login varchar(60),
    usuario_nombre varchar(120)
);

-- Ayuda en pantalla (agregado despues): columnas nuevas de usuario. En una
-- base que ya las tiene no hace nada; en una base anterior las agrega, con
-- la ayuda prendida para todos.
ALTER TABLE usuario ADD COLUMN IF NOT EXISTS mostrar_ayuda boolean DEFAULT true NOT NULL;
ALTER TABLE usuario ADD COLUMN IF NOT EXISTS tour_visto boolean DEFAULT false NOT NULL;
